services:
  mobile:
    build: mobile
    image: hubmi/mobile
    profiles: [mobile, services]
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
      - path: mobile/.env
        required: false
