POWIATS: dict[str, str] = {
    "krakow": "Kraków",
    "nowy-sacz": "Nowy Sącz",
    "tarnow": "Tarnów",
    "powiat-bochenski": "powiat bocheński",
    "powiat-brzeski": "powiat brzeski",
    "powiat-chrzanowski": "powiat chrzanowski",
    "powiat-dabrowski": "powiat dąbrowski",
    "powiat-gorlicki": "powiat gorlicki",
    "powiat-krakowski": "powiat krakowski",
    "powiat-limanowski": "powiat limanowski",
    "powiat-miechowski": "powiat miechowski",
    "powiat-myslenicki": "powiat myślenicki",
    "powiat-nowosadecki": "powiat nowosądecki",
    "powiat-nowotarski": "powiat nowotarski",
    "powiat-olkuski": "powiat olkuski",
    "powiat-oswiecimski": "powiat oświęcimski",
    "powiat-proszowicki": "powiat proszowicki",
    "powiat-suski": "powiat suski",
    "powiat-tarnowski": "powiat tarnowski",
    "powiat-tatrzanski": "powiat tatrzański",
    "powiat-wadowicki": "powiat wadowicki",
    "powiat-wielicki": "powiat wielicki",
}
